title: Guide to Top Predocs
description: A guide for Middlebury students aspiring to work at top Economics predoc programs
theme: just-the-docs

url: https://zhizhongpu.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
