title: Top Predoc Guide
description: A guide for Middlebury students aspiring to work at top Economics predoc programs
theme: just-the-docs

url: https://zhizhongpu.github.io

aux_links:
  Contact: https://zhizhongpu.github.io/predocguide/about.html
